### ISSUE TITLE
多用户签到的一个可能的风险

### ISSUE THREAD

**Issue by chitsanfei** [Clansty/superstar-checkin#8]
### Basic Information
- System: Windows Server 2016
- Version: main [2b8e6e0](https://github.com/Clansty/superstar-checkin/commit/2b8e6e0c9d25af0f0f8044b20dbbd7ea10c51be5)
- Log: -
- Node Version: v16.13.1
- Bot Report: -

### Description
多用户签到以第一个用户的课程信息为准的话，第一个用户有而其他用户没有的课程，在课程签到信息发布后，其他用户也会签到，即使他们不在课程内，这个设计感觉挺危险的。

**Comment by HankMo** [comment]
怎么部署 可以留个联系方式 教一下我嘛，我自己弄一直出错

**Comment by chitsanfei** [comment]
>  怎么部署 可以留个联系方式 教一下我嘛，我自己弄一直出错

readme里面不是把部署方式写明白了么 🤔

**Comment by HankMo** [comment]
![image](https://user-images.githubusercontent.com/60347960/161518343-480c3dfd-48b2-4dae-850e-31ef5e6de8a2.png)

**Comment by HankMo** [comment]
配置文件这样写对吗

**Comment by chitsanfei** [comment]
> 配置文件这样写对吗

把不需要的配置项用#注释掉
中文前面也加上#
courseid如果不需要地理位置签到就无需去指定，也注释掉就可
还有乖宝你爪鸡号和密码漏了 😐

**Comment by chitsanfei** [comment]
> 配置文件这样写对吗

给你个参考吧

```
bot:
  uin: 114514
  password: 1919810
  notifyGroups:
    - 1919810
  qrcodeGroups:
    - 1919810
  ignore:
    - 
ignoreCourses:
  - 
geoLocations:
#  - courseId:
#    lat: 114.5140
#    lon: 514.1919
#    address: 下北泽
#  - courseId: 另一门课的 ID，假装这门课不同天在不同的地方上课
#    lat: 经度
#    lon: 纬度，请务必用 Readme 中的百度地图工具查询
#    address: 地图显示的地址，建议去实地发个签到查看学习通上显示的地址
#    onlyOnWeekdays:
#      # 数字表示的星期，0：周日，1：周一...
#      - 1
#  - courseId: 还是刚刚那一门课的 ID，这里写的是不在上一条那些天里面的地理位置
#    lat: 另外的经度
#    lon: 另外的纬度
#    address: 更上面的更优先，同一门课程请把没有 onlyOnWeekdays 的写在最下面
# 可以配置多个账号，将使用第一个账号获取签到信息，所以第一个账号的课需要是全的
accounts:
  - username: 1145141919810
    password: 1145141919810

```
